query GetFollowingEvents($id: uuid!) {
  events(
    where: { events_followers: { user_id: { _eq: $id } } }
    order_by: { end_date: desc }
  ) {
    address
    capacity
    category_id
    description
    end_date
    event_images
    id
    is_free
    location
    price
    start_date
    title
    uid
    venue
  }
}
