query GetEvents {
  events(order_by: { end_date: asc }) {
    address
    capacity
    category_id
    description
    end_date
    event_images
    id
    is_free
    location
    price
    start_date
    title
    uid
    venue
  }
}
