query GetEvents($limit: Int, $offset: Int, $filter: events_bool_exp) {
  events(
    limit: $limit
    offset: $offset
    where: $filter
    order_by: { end_date: asc }
  ) {
    address
    capacity
    category_id
    description
    end_date
    event_images
    events_bookmarks {
      created_at
      event_id
      id
      user_id
    }
    events_category {
      description
      id
      name
    }
    events_followers {
      event_id
      id
      user_id
    }
    events_tickets {
      event_id
      id
      created_at
      status
      user_id
    }
    id
    location
    is_free
    price
    start_date
    title
    uid
    venue
    created_at
  }
}
